myproject/urls.py
# myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('technicians/', include('technicians.urls')),
]

technicians/urls.py
# technicians/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.menu_view, name='menu'),
    path('task-form/', views.task_form, name='task_form'),
    path('monthly-reports/', views.monthly_reports, name='monthly_reports'),
     path('download-csv/', views.download_monthly_report_csv, name='download_csv'),
     path('download-pdf/', views.download_pdf_report, name='download_pdf'),


]

technicians/models.py
from django.db import models

class Task(models.Model):
    start_time = models.TimeField()
    description = models.TextField()
    equipment_lot = models.CharField(max_length=100)
    technician_name = models.CharField(max_length=50)
    location = models.CharField(max_length=100)
    date = models.DateField()

    def __str__(self):
        return f"Task #{self.id} - {self.description}"

    class Meta:
        app_label = 'technicians'  # Specify the app_label for this model

technicians/views.py
# technicians/views.py
from django.shortcuts import render, redirect
from .form import TaskForm
from .models import Task

# views.py

from django.shortcuts import render, redirect
from .models import Task
from .form import TaskForm

def task_form(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()  # Save the form data to the database
            return redirect('monthly_reports')  # Redirect to monthly reports page
    else:
        form = TaskForm()
    return render(request, 'task_form.html', {'form': form})

def monthly_reports(request):
    tasks = Task.objects.all()  # Retrieve all tasks from the database
    return render(request, 'monthly_reports.html', {'tasks': tasks})
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from .models import Task

import csv
from django.http import HttpResponse
from .models import Task

def download_monthly_report_csv(request):
    # Fetch monthly report data (e.g., tasks)
    tasks = Task.objects.all()

    # Prepare CSV response
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="monthly_report.csv"'

    # Define CSV writer
    writer = csv.writer(response)
    
    # Write CSV header
    writer.writerow(['Description', 'Date', 'Technician Name', 'Location','start time'])

    # Write CSV rows
    for task in tasks:
        writer.writerow([task.description, task.date, task.technician_name, task.location,task.start_time])

    return response
# views.py
import os
from django.http import HttpResponse
from django.conf import settings
from .models import Task
from .pdf_generator import generate_pdf_report

def download_pdf_report(request):
    try:
        # Retrieve tasks from the database
        tasks = Task.objects.all()

        # Generate the PDF report
        pdf_file_path = generate_pdf_report(tasks)

        # Serve the generated PDF file as a download
        with open(pdf_file_path, "rb") as pdf_file:
            response = HttpResponse(pdf_file.read(), content_type="application/pdf")
            response["Content-Disposition"] = 'attachment; filename="rapport.pdf"'
            return response

    except Task.DoesNotExist:
        return HttpResponse("No tasks found.", status=404)

    except Exception as e:
        return HttpResponse(f"Error generating or serving PDF: {str(e)}", status=500)

    finally:
        # Clean up: Remove the generated PDF file after serving
        if pdf_file_path and os.path.exists(pdf_file_path):
            os.remove(pdf_file_path)
from django.shortcuts import render

def menu_view(request):
    return render(request, 'menu.html')

technicians/templates/menu.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<!-- Structure HTML du menu -->
<nav>


        <ul>
            <li class="deroulant"><a href="{% url 'task_form' %}">Formulaire du Rendement quotidien &ensp;</a></li>
            <li class="deroulant"><a href="{% url 'monthly_reports' %}">Rapports Mensuels &ensp;</a></li>
            <!-- Ajoutez d'autres liens de menu ici -->
            <li><a href="#">Contact</a></li>
            <li><a href="#">À propos</a></li>
        </ul>
    </div>
</nav>



</body>
</html>

technicians/templates/monthly_reports.html
<!-- monthly_reports.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Rapport</title>
    <style>
        /* CSS for styling */
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0; /* Light gray background */
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff; /* White background for main content */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Shadow effect */
        }
        h1 {
            text-align: center;
            color: #007bff; /* Blue color for title */
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        table th {
            background-color: #007bff; /* Blue background for table headers */
            color: #fff; /* White text color for table headers */
        }
        .logo {
            max-width: 100px;
            margin-right: 20px; /* Add right margin for spacing */
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Rapport Mensuel</h1>
        <table>
            <thead>
                <tr>
                    <th>Heure de Début</th>
                    <th>Date</th>
                    <th>Description</th>
                    <th>Nom du Technicien</th>
                    <th>Emplacement</th>
                    <th>Équipement/Lot</th>
                </tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                <tr>
                    <td>{{ task.start_time }}</td>
                    <td>{{ task.date }}</td>
                    <td>{{ task.description }}</td>
                    <td>{{ task.technician_name }}</td>
                    <td>{{ task.location }}</td>
                    <td>{{ task.equipment_lot }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6">Aucune tâche enregistrée.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'download_csv' %}" download>Télécharger le rapport CSV</a>
        <a href="{% url 'download_pdf' %}" download>Télécharger le rapport PDF</a>
    </div>
</body>
</html>

technicians/templates/task_form.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulaire de Performance Quotidienne</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Datepicker CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet">

    <style>
        body {
            background-color: #f0f7ff; /* Couleur de fond bleu clair */
            padding-top: 50px; /* Ajouter un padding en haut */
        }
        .container {
            max-width: 600px; /* Largeur maximale du conteneur du formulaire */
            background-color: #ffffff; /* Fond blanc pour le formulaire */
            padding: 30px; /* Ajouter du padding à l'intérieur du conteneur */
            border-radius: 10px; /* Ajouter un bord arrondi */
            box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.1);
            color: #3e6eb0; /* Couleur du texte principale */
        }
        .form-control {
            border-color: #6c8cdd; /* Couleur de bordure bleue pour les contrôles du formulaire */
        }
        .btn-primary {
            background-color: #3e6eb0; /* Fond de bouton bleu foncé */
            border-color: #3e6eb0; /* Couleur de bordure du bouton bleu foncé */
        }
        .btn-primary:hover {
            background-color: #345492; /* Bleu plus foncé au survol */
            border-color: #345492;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1 class="mb-4">Rendement Quotidienne</h1>
        <form method="post" action="{% url 'task_form' %}" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_start_time" class="form-label">Heure de Début :</label>
                {{ form.start_time }}
            </div>
            <div class="mb-3">
                <label for="id_description" class="form-label">Description :</label>
                <textarea class="form-control" id="id_description" name="description" rows="4" maxlength="200" placeholder="Entrez la description..." required></textarea>
                <small class="text-muted"><span id="charCount">0</span>/200 caractères maximum</small>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <label for="id_equipment_lot" class="form-label">Équipement/Lot :</label>
                    <select class="form-select" id="id_equipment_lot" name="equipment_lot">
                        <option value="" selected disabled>Sélectionnez l'Équipement/Lot</option>
                        <option value="Plomberie">Plomberie</option>
                        <option value="Climatisation">Climatisation</option>
                        <option value="Menuiserie">Menuiserie</option>
                        <option value="Détection Incendie">Détection Incendie</option>
                        <option value="Électricité">Électricité</option>
                        <option value="SOE">SOE</option>
                    </select>
                </div>
                <div class="col">
                    <label for="id_technician_name" class="form-label">Nom du Technicien :</label>
                    <!-- Menu déroulant pour le nom du technicien -->
                    <select class="form-select" id="id_technician_name" name="technician_name">
                        <option value="" selected disabled>Sélectionnez le Technicien</option>
                        <option value="Technicien 1">Mandor</option>
                        <option value="Technicien 2">Majidi</option>
                        <option value="Technicien 3">Otmani</option>
                    </select>
                </div>
            </div>
            <div class="mb-3">
                <label for="id_location" class="form-label">Emplacement :</label>
                <select class="form-select" id="id_location" name="location">
                    <option value="" selected disabled>Sélectionnez l'Emplacement</option>
                    <option value="Bâtiment">Bâtiment</option>
                    <option value="Cafétéria Nissan">Cafétéria Nissan</option>
                    <option value="Cafétéria Renault">Cafétéria Renault</option>
                    <option value="HJD">HJD</option>
                    <option value="IMC">IMC</option>
                    <option value="Salle d'Infirmier">Salle d'Infirmier</option>
                    <option value="Toiture">Toiture</option>
                    <option value="Vestiaire Nissan">Vestiaire Nissan</option>
                    <option value="MAF">MAF</option>
                    <option value="Local IT">Local IT</option>
                    <option value="Open Space">Open Space</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="id_date" class="form-label">Date :</label>
                <input type="text" class="form-control" id="id_date" name="date" placeholder="Sélectionnez une date" required>
            </div>
            
            <button type="submit" class="btn btn-primary">Soumettre</button>
        </form>
    </div>

    <!-- Bootstrap JS et jQuery (nécessaires pour les plugins JavaScript de Bootstrap) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Bootstrap Datepicker JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <script>
        // Initialisation du sélecteur de date pour le champ 'date'
        $(document).ready(function() {
            $('#id_date').datepicker({
                format: 'yyyy-mm-dd',  // Format de date
                autoclose: true,       // Fermer le sélecteur de date après la sélection
                todayHighlight: true   // Mettre en surbrillance la date d'aujourd'hui
            });

            // Compteur de caractères pour le champ de description
            $('#id_description').on('input', function() {
                var charCount = $(this).val().length;
                $('#charCount').text(charCount);
            });
        });
    </script>
</body>
</html>